In [2]:
import pandas as pd
import numpy as np
import math
import statsmodels.formula.api as smf
import statsmodels.stats.api as sms

In [3]:
df = pd.read_csv('botswana.tsv', sep = '\t', header = 0)
df.head()

,ceb,age,educ,religion,idlnchld,knowmeth,usemeth,evermarr,agefm,heduc,urban,electric,radio,tv,bicycle
0,0,18,10,catholic,4.0,1.0,1.0,0,NaN,NaN,1,1.0,1.0,1.0,1.0
1,2,43,11,protestant,2.0,1.0,1.0,1,20.0,14.0,1,1.0,1.0,1.0,1.0
2,0,49,4,spirit,4.0,1.0,0.0,1,22.0,1.0,1,1.0,1.0,0.0,0.0
3,0,24,12,other,2.0,1.0,0.0,0,NaN,NaN,1,1.0,1.0,1.0,1.0
4,3,32,13,other,3.0,1.0,1.0,1,24.0,12.0,1,1.0,1.0,1.0,1.0

In [4]:
print df.columns

Index([u'ceb', u'age', u'educ', u'religion', u'idlnchld', u'knowmeth',
       u'usemeth', u'evermarr', u'agefm', u'heduc', u'urban', u'electric',
       u'radio', u'tv', u'bicycle'],
      dtype='object')

Загрузите данные и внимательно изучите их. Сколько разных значений принимает признак religion?

In [5]:
print df.religion.value_counts()

spirit        1841
other         1080
protestant     993
catholic       447
Name: religion, dtype: int64

Во многих признаках есть пропущенные значения. Сколько объектов из 4361 останется, если выбросить все, содержащие пропуски?

In [6]:
df.index

RangeIndex(start=0, stop=4361, step=1)

In [7]:
df.dropna()

,ceb,age,educ,religion,idlnchld,knowmeth,usemeth,evermarr,agefm,heduc,urban,electric,radio,tv,bicycle
1,2,43,11,protestant,2.0,1.0,1.0,1,20.0,14.0,1,1.0,1.0,1.0,1.0
2,0,49,4,spirit,4.0,1.0,0.0,1,22.0,1.0,1,1.0,1.0,0.0,0.0
4,3,32,13,other,3.0,1.0,1.0,1,24.0,12.0,1,1.0,1.0,1.0,1.0
5,1,30,5,spirit,5.0,1.0,0.0,1,24.0,7.0,1,1.0,0.0,0.0,0.0
6,3,42,4,other,3.0,1.0,0.0,1,15.0,11.0,1,1.0,0.0,1.0,0.0
7,1,36,7,other,4.0,1.0,1.0,1,24.0,9.0,1,1.0,0.0,0.0,0.0
8,4,37,16,catholic,4.0,1.0,1.0,1,26.0,17.0,1,1.0,1.0,1.0,1.0
9,1,34,5,protestant,4.0,1.0,1.0,1,18.0,3.0,1,0.0,1.0,0.0,0.0
10,3,42,15,other,3.0,1.0,1.0,1,24.0,16.0,1,1.0,1.0,1.0,1.0
11,3,29,7,spirit,6.0,1.0,1.0,1,24.0,7.0,1,1.0,1.0,0.0,0.0
13,10,48,4,protestant,4.0,1.0,1.0,1,26.0,3.0,1,1.0,1.0,0.0,0.0
14,3,35,12,protestant,3.0,1.0,1.0,1,21.0,16.0,1,1.0,1.0,1.0,1.0
18,0,32,16,protestant,2.0,1.0,1.0,1,25.0,16.0,1,1.0,1.0,1.0,0.0
19,1,27,12,spirit,3.0,1.0,1.0,1,23.0,16.0,1,1.0,1.0,1.0,0.0
20,0,23,12,protestant,2.0,1.0,1.0,1,18.0,12.0,1,1.0,1.0,1.0,0.0
21,4,39,11,protestant,4.0,1.0,0.0,1,23.0,16.0,1,1.0,1.0,1.0,1.0
22,2,38,12,other,4.0,1.0,0.0,1,25.0,14.0,1,1.0,1.0,1.0,1.0
23,4,39,6,spirit,4.0,1.0,0.0,1,18.0,10.0,1,1.0,1.0,0.0,1.0
25,2,43,16,protestant,4.0,1.0,1.0,1,22.0,15.0,1,1.0,1.0,1.0,1.0
26,6,41,13,protestant,6.0,1.0,1.0,1,18.0,15.0,1,1.0,1.0,1.0,1.0
30,3,49,12,spirit,3.0,1.0,1.0,1,21.0,15.0,1,1.0,1.0,1.0,1.0
34,4,25,5,other,4.0,1.0,1.0,1,21.0,14.0,1,0.0,0.0,0.0,0.0
37,2,40,12,catholic,2.0,1.0,1.0,1,25.0,15.0,1,1.0,1.0,1.0,1.0
38,5,40,7,spirit,5.0,1.0,1.0,1,17.0,0.0,1,1.0,1.0,0.0,1.0
40,1,33,12,other,4.0,1.0,1.0,1,22.0,12.0,1,1.0,1.0,0.0,0.0
42,2,41,12,protestant,2.0,1.0,1.0,1,23.0,13.0,1,1.0,1.0,1.0,0.0
46,1,25,12,catholic,2.0,1.0,1.0,1,25.0,14.0,1,1.0,1.0,1.0,0.0
47,3,48,12,catholic,4.0,1.0,0.0,1,30.0,15.0,1,1.0,1.0,1.0,1.0
48,3,32,14,catholic,3.0,1.0,1.0,1,22.0,14.0,1,1.0,1.0,1.0,1.0
49,3,27,10,protestant,3.0,0.0,0.0,1,17.0,7.0,1,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4290,0,32,2,protestant,4.0,1.0,0.0,1,30.0,0.0,0,0.0,1.0,0.0,0.0
4292,2,24,9,other,4.0,1.0,1.0,1,22.0,10.0,0,0.0,1.0,0.0,0.0
4295,7,47,0,spirit,8.0,0.0,0.0,1,36.0,0.0,0,0.0,0.0,0.0,0.0
4296,4,44,0,other,14.0,0.0,0.0,1,14.0,0.0,0,0.0,1.0,0.0,1.0
4297,6,36,0,catholic,6.0,1.0,1.0,1,17.0,7.0,0,0.0,1.0,0.0,0.0
4298,5,32,7,protestant,4.0,1.0,1.0,1,21.0,0.0,0,0.0,1.0,0.0,0.0
4301,5,28,0,protestant,3.0,1.0,1.0,1,13.0,0.0,0,0.0,0.0,0.0,0.0
4302,4,36,0,protestant,8.0,1.0,0.0,1,26.0,0.0,0,0.0,0.0,0.0,0.0
4303,1,25,0,protestant,6.0,1.0,0.0,1,19.0,0.0,0,0.0,1.0,0.0,0.0
4304,4,27,2,protestant,4.0,1.0,1.0,1,21.0,0.0,0,0.0,0.0,0.0,0.0
4305,11,41,7,protestant,15.0,1.0,1.0,1,20.0,1.0,0,0.0,1.0,0.0,0.0
4306,7,44,3,protestant,6.0,1.0,1.0,1,17.0,4.0,0,1.0,0.0,0.0,0.0
4307,2,26,10,other,6.0,1.0,1.0,1,18.0,7.0,0,0.0,1.0,0.0,0.0
4310,2,25,5,spirit,10.0,1.0,0.0,1,16.0,0.0,0,0.0,1.0,0.0,0.0
4315,7,44,0,protestant,7.0,1.0,1.0,1,16.0,0.0,0,0.0,0.0,0.0,0.0
4318,4,38,0,protestant,4.0,1.0,0.0,1,16.0,0.0,0,0.0,0.0,0.0,0.0
4319,1,22,7,protestant,4.0,1.0,0.0,1,19.0,0.0,0,0.0,0.0,0.0,0.0
4321,1,21,7,protestant,4.0,1.0,1.0,1,18.0,10.0,0,0.0,1.0,0.0,1.0
4323,1,23,7,protestant,4.0,1.0,1.0,1,21.0,7.0,0,0.0,1.0,0.0,0.0
4324,2,22,2,protestant,5.0,1.0,1.0,1,20.0,0.0,0,0.0,0.0,0.0,0.0
4326,3,27,10,protestant,3.0,1.0,1.0,1,19.0,12.0,0,0.0,1.0,0.0,0.0
4328,5,28,0,spirit,6.0,1.0,0.0,1,17.0,0.0,0,0.0,0.0,0.0,0.0
4342,4,28,0,protestant,4.0,1.0,1.0,1,19.0,0.0,0,0.0,0.0,0.0,0.0
4344,5,33,0,protestant,6.0,0.0,0.0,1,30.0,0.0,0,0.0,1.0,0.0,0.0
4346,5,32,0,protestant,3.0,1.0,1.0,1,16.0,0.0,0,0.0,1.0,0.0,0.0
4353,9,49,0,protestant,5.0,0.0,0.0,1,15.0,0.0,0,0.0,1.0,0.0,0.0
4354,3,31,2,protestant,4.0,1.0,1.0,1,18.0,0.0,0,0.0,1.0,0.0,0.0
4355,4,27,6,protestant,4.0,1.0,1.0,1,17.0,7.0,0,0.0,0.0,0.0,0.0
4359,1,26,0,spirit,5.0,1.0,0.0,1,22.0,7.0,0,0.0,1.0,0.0,0.0
4360,6,36,3,protestant,8.0,1.0,1.0,1,21.0,0.0,0,0.0,1.0,0.0,0.0

Создайте признак nevermarr, равный единице там, где в agefm пропуски.

In [7]:
new_df = df.copy()
new_df.loc[new_df['agefm'].isnull(),'nevermarr']=1
new_df['nevermarr'].fillna(0,inplace=True)
print new_df.nevermarr.value_counts()

1.0    2282
0.0    2079
Name: nevermarr, dtype: int64

In [8]:
new_df.head()

,ceb,age,educ,religion,idlnchld,knowmeth,usemeth,evermarr,agefm,heduc,urban,electric,radio,tv,bicycle,nevermarr
0,0,18,10,catholic,4.0,1.0,1.0,0,NaN,NaN,1,1.0,1.0,1.0,1.0,1.0
1,2,43,11,protestant,2.0,1.0,1.0,1,20.0,14.0,1,1.0,1.0,1.0,1.0,0.0
2,0,49,4,spirit,4.0,1.0,0.0,1,22.0,1.0,1,1.0,1.0,0.0,0.0,0.0
3,0,24,12,other,2.0,1.0,0.0,0,NaN,NaN,1,1.0,1.0,1.0,1.0,1.0
4,3,32,13,other,3.0,1.0,1.0,1,24.0,12.0,1,1.0,1.0,1.0,1.0,0.0

Удалите признак evermarr — в сумме с nevermarr он даёт константу, значит, в нашей матрице XXX будет мультиколлинеарность.

In [9]:
new_df.drop(['evermarr'],axis=1, inplace=True)

In [10]:
new_df.head()

,ceb,age,educ,religion,idlnchld,knowmeth,usemeth,agefm,heduc,urban,electric,radio,tv,bicycle,nevermarr
0,0,18,10,catholic,4.0,1.0,1.0,NaN,NaN,1,1.0,1.0,1.0,1.0,1.0
1,2,43,11,protestant,2.0,1.0,1.0,20.0,14.0,1,1.0,1.0,1.0,1.0,0.0
2,0,49,4,spirit,4.0,1.0,0.0,22.0,1.0,1,1.0,1.0,0.0,0.0,0.0
3,0,24,12,other,2.0,1.0,0.0,NaN,NaN,1,1.0,1.0,1.0,1.0,1.0
4,3,32,13,other,3.0,1.0,1.0,24.0,12.0,1,1.0,1.0,1.0,1.0,0.0

Замените NaN в признаке agefm на cagefm=0c_{agefm}=0cagefm​=0.

In [11]:
new_df.loc[new_df['agefm'].isnull(),'agefm']=0

In [12]:
new_df.head()

,ceb,age,educ,religion,idlnchld,knowmeth,usemeth,agefm,heduc,urban,electric,radio,tv,bicycle,nevermarr
0,0,18,10,catholic,4.0,1.0,1.0,0.0,NaN,1,1.0,1.0,1.0,1.0,1.0
1,2,43,11,protestant,2.0,1.0,1.0,20.0,14.0,1,1.0,1.0,1.0,1.0,0.0
2,0,49,4,spirit,4.0,1.0,0.0,22.0,1.0,1,1.0,1.0,0.0,0.0,0.0
3,0,24,12,other,2.0,1.0,0.0,0.0,NaN,1,1.0,1.0,1.0,1.0,1.0
4,3,32,13,other,3.0,1.0,1.0,24.0,12.0,1,1.0,1.0,1.0,1.0,0.0

У объектов, где nevermarr = 1, замените NaN в признаке heduc на cheduc1=−1c_{heduc_1}=-1cheduc1​​=−1 (ноль использовать нельзя, так как он уже встречается у некоторых объектов выборки).

In [13]:
new_df.heduc.isna().sum()

2405

In [14]:
new_df.loc[(new_df['nevermarr']==1),'heduc']=-1

In [15]:
new_df.heduc.isna().sum()

123

In [16]:
new_df.head()

,ceb,age,educ,religion,idlnchld,knowmeth,usemeth,agefm,heduc,urban,electric,radio,tv,bicycle,nevermarr
0,0,18,10,catholic,4.0,1.0,1.0,0.0,-1.0,1,1.0,1.0,1.0,1.0,1.0
1,2,43,11,protestant,2.0,1.0,1.0,20.0,14.0,1,1.0,1.0,1.0,1.0,0.0
2,0,49,4,spirit,4.0,1.0,0.0,22.0,1.0,1,1.0,1.0,0.0,0.0,0.0
3,0,24,12,other,2.0,1.0,0.0,0.0,-1.0,1,1.0,1.0,1.0,1.0,1.0
4,3,32,13,other,3.0,1.0,1.0,24.0,12.0,1,1.0,1.0,1.0,1.0,0.0

Избавимся от оставшихся пропусков.

Для признаков idlnchld, heduc и usemeth проведите операцию, аналогичную предыдущей: создайте индикаторы пропусков по этим признакам (idlnchld_noans, heduc_noans, usemeth_noans), замените пропуски на нехарактерные значения (cidlnchld=−1c_{idlnchld}=-1cidlnchld​=−1, cheduc2=−2c_{heduc_2}=-2cheduc2​​=−2 (значение -1 мы уже использовали), cusemeth=−1c_{usemeth}=-1cusemeth​=−1).

Остались только пропуски в признаках knowmeth, electric, radio, tv и bicycle. Их очень мало, так что удалите объекты, на которых их значения пропущены.

Какого размера теперь наша матрица данных? Умножьте количество строк на количество всех столбцов (включая отклик ceb).

In [17]:
new_df['idlnchld_noans'] = new_df['idlnchld'].apply(lambda x : 1 if (math.isnan(x)) else 0)
new_df['heduc_noans'] = new_df['heduc'].apply(lambda x : 1 if (math.isnan(x)) else 0)
new_df['usemeth_noans'] = new_df['usemeth'].apply(lambda x : 1 if (math.isnan(x)) else 0)

In [18]:
values = {'idlnchld': -1, 'heduc': -2, 'usemeth': -1}

In [19]:
new_df.fillna(value=values, inplace=True)

In [20]:
new_df.head()

,ceb,age,educ,religion,idlnchld,knowmeth,usemeth,agefm,heduc,urban,electric,radio,tv,bicycle,nevermarr,idlnchld_noans,heduc_noans,usemeth_noans
0,0,18,10,catholic,4.0,1.0,1.0,0.0,-1.0,1,1.0,1.0,1.0,1.0,1.0,0,0,0
1,2,43,11,protestant,2.0,1.0,1.0,20.0,14.0,1,1.0,1.0,1.0,1.0,0.0,0,0,0
2,0,49,4,spirit,4.0,1.0,0.0,22.0,1.0,1,1.0,1.0,0.0,0.0,0.0,0,0,0
3,0,24,12,other,2.0,1.0,0.0,0.0,-1.0,1,1.0,1.0,1.0,1.0,1.0,0,0,0
4,3,32,13,other,3.0,1.0,1.0,24.0,12.0,1,1.0,1.0,1.0,1.0,0.0,0,0,0

In [21]:
new_df.dropna(inplace=True)

In [22]:
new_df.head()

,ceb,age,educ,religion,idlnchld,knowmeth,usemeth,agefm,heduc,urban,electric,radio,tv,bicycle,nevermarr,idlnchld_noans,heduc_noans,usemeth_noans
0,0,18,10,catholic,4.0,1.0,1.0,0.0,-1.0,1,1.0,1.0,1.0,1.0,1.0,0,0,0
1,2,43,11,protestant,2.0,1.0,1.0,20.0,14.0,1,1.0,1.0,1.0,1.0,0.0,0,0,0
2,0,49,4,spirit,4.0,1.0,0.0,22.0,1.0,1,1.0,1.0,0.0,0.0,0.0,0,0,0
3,0,24,12,other,2.0,1.0,0.0,0.0,-1.0,1,1.0,1.0,1.0,1.0,1.0,0,0,0
4,3,32,13,other,3.0,1.0,1.0,24.0,12.0,1,1.0,1.0,1.0,1.0,0.0,0,0,0

In [23]:
print len(new_df.columns)
print len(new_df)
print len(new_df.columns)*len(new_df)

18
4348
78264

In [24]:
new_df.to_csv('pandas.csv', sep='\t')

In [25]:
m1 = smf.ols('ceb ~ age + educ + religion + idlnchld + knowmeth + usemeth + agefm +'\
                    'heduc + urban + electric + radio + tv + bicycle + nevermarr +'\
                    'idlnchld_noans + heduc_noans + usemeth_noans', 
             data=new_df)
fitted1 = m1.fit(cov_type='HC1')
print fitted1.summary()

                            OLS Regression Results
==============================================================================
Dep. Variable:                    ceb   R-squared:                       0.644
Model:                            OLS   Adj. R-squared:                  0.643
Method:                 Least Squares   F-statistic:                     345.0
Date:                Mon, 06 May 2019   Prob (F-statistic):               0.00
Time:                        16:52:37   Log-Likelihood:                -7732.1
No. Observations:                4348   AIC:                         1.550e+04
Df Residuals:                    4328   BIC:                         1.563e+04
Df Model:                          19
Covariance Type:                  HC1
==========================================================================================
                             coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------------------
Intercept                 -1.0263      0.266     -3.863      0.000      -1.547      -0.506
religion[T.other]         -0.0830      0.078     -1.067      0.286      -0.235       0.069
religion[T.protestant]    -0.0149      0.078     -0.192      0.848      -0.167       0.137
religion[T.spirit]        -0.0191      0.071     -0.268      0.789      -0.159       0.121
age                        0.1703      0.004     38.627      0.000       0.162       0.179
educ                      -0.0724      0.007     -9.924      0.000      -0.087      -0.058
idlnchld                   0.0760      0.015      5.236      0.000       0.048       0.104
knowmeth                   0.5564      0.174      3.190      0.001       0.215       0.898
usemeth                    0.6473      0.052     12.478      0.000       0.546       0.749
agefm                     -0.0604      0.010     -6.174      0.000      -0.080      -0.041
heduc                     -0.0551      0.009     -6.126      0.000      -0.073      -0.037
urban                     -0.2137      0.046     -4.667      0.000      -0.303      -0.124
electric                  -0.2685      0.072     -3.732      0.000      -0.410      -0.128
radio                     -0.0235      0.053     -0.446      0.656      -0.127       0.080
tv                        -0.1451      0.082     -1.766      0.077      -0.306       0.016
bicycle                    0.2139      0.048      4.412      0.000       0.119       0.309
nevermarr                 -2.2393      0.202    -11.082      0.000      -2.635      -1.843
idlnchld_noans             0.6539      0.216      3.029      0.002       0.231       1.077
heduc_noans               -0.8724      0.191     -4.556      0.000      -1.248      -0.497
usemeth_noans              0.7652      0.213      3.590      0.000       0.347       1.183
==============================================================================
Omnibus:                      224.411   Durbin-Watson:                   1.887
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              859.014
Skew:                           0.003   Prob(JB):                    2.93e-187
Kurtosis:                       5.178   Cond. No.                         361.
==============================================================================

Warnings:
[1] Standard Errors are heteroscedasticity robust (HC1)

In [26]:
print sms.het_breuschpagan(fitted1.resid, fitted1.model.exog)[1]

1.1452927633439797e-225

In [27]:
new_df.drop(['religion', 'radio', 'tv'],axis=1, inplace=True)
new_df.head()

,ceb,age,educ,idlnchld,knowmeth,usemeth,agefm,heduc,urban,electric,bicycle,nevermarr,idlnchld_noans,heduc_noans,usemeth_noans
0,0,18,10,4.0,1.0,1.0,0.0,-1.0,1,1.0,1.0,1.0,0,0,0
1,2,43,11,2.0,1.0,1.0,20.0,14.0,1,1.0,1.0,0.0,0,0,0
2,0,49,4,4.0,1.0,0.0,22.0,1.0,1,1.0,0.0,0.0,0,0,0
3,0,24,12,2.0,1.0,0.0,0.0,-1.0,1,1.0,1.0,1.0,0,0,0
4,3,32,13,3.0,1.0,1.0,24.0,12.0,1,1.0,1.0,0.0,0,0,0

In [28]:
m2 = smf.ols('ceb ~ age + educ + idlnchld + knowmeth + usemeth + agefm +'\
                    'heduc + urban + electric + bicycle + nevermarr +'\
                    'idlnchld_noans + heduc_noans + usemeth_noans', 
             data=new_df)
fitted2 = m2.fit(cov_type='HC1')
print fitted2.summary()

                            OLS Regression Results
==============================================================================
Dep. Variable:                    ceb   R-squared:                       0.644
Model:                            OLS   Adj. R-squared:                  0.643
Method:                 Least Squares   F-statistic:                     463.4
Date:                Mon, 06 May 2019   Prob (F-statistic):               0.00
Time:                        16:52:37   Log-Likelihood:                -7734.5
No. Observations:                4348   AIC:                         1.550e+04
Df Residuals:                    4333   BIC:                         1.559e+04
Df Model:                          14
Covariance Type:                  HC1
==================================================================================
                     coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept         -1.0698      0.258     -4.152      0.000      -1.575      -0.565
age                0.1702      0.004     38.746      0.000       0.162       0.179
educ              -0.0729      0.007    -10.311      0.000      -0.087      -0.059
idlnchld           0.0770      0.014      5.323      0.000       0.049       0.105
knowmeth           0.5610      0.174      3.224      0.001       0.220       0.902
usemeth            0.6516      0.052     12.571      0.000       0.550       0.753
agefm             -0.0606      0.010     -6.192      0.000      -0.080      -0.041
heduc             -0.0573      0.009     -6.440      0.000      -0.075      -0.040
urban             -0.2190      0.045     -4.814      0.000      -0.308      -0.130
electric          -0.3207      0.063     -5.076      0.000      -0.445      -0.197
bicycle            0.2046      0.048      4.279      0.000       0.111       0.298
nevermarr         -2.2501      0.202    -11.158      0.000      -2.645      -1.855
idlnchld_noans     0.6565      0.216      3.043      0.002       0.234       1.079
heduc_noans       -0.8853      0.191     -4.638      0.000      -1.259      -0.511
usemeth_noans      0.7732      0.212      3.639      0.000       0.357       1.190
==============================================================================
Omnibus:                      224.096   Durbin-Watson:                   1.886
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              856.760
Skew:                           0.004   Prob(JB):                    9.06e-187
Kurtosis:                       5.175   Cond. No.                         345.
==============================================================================

Warnings:
[1] Standard Errors are heteroscedasticity robust (HC1)

In [29]:
print sms.het_breuschpagan(fitted2.resid, fitted2.model.exog)[1]

1.1197458896534061e-228

In [30]:
m3 = smf.ols('ceb ~ age + educ + idlnchld + knowmeth + usemeth + agefm +'\
                    'heduc + urban + electric + bicycle + nevermarr +'\
                    'idlnchld_noans + heduc_noans + usemeth_noans', 
                    data=new_df)
fitted3 = m3.fit(cov_type='HC1')
print fitted3.summary()

                            OLS Regression Results
==============================================================================
Dep. Variable:                    ceb   R-squared:                       0.644
Model:                            OLS   Adj. R-squared:                  0.643
Method:                 Least Squares   F-statistic:                     463.4
Date:                Mon, 06 May 2019   Prob (F-statistic):               0.00
Time:                        16:52:37   Log-Likelihood:                -7734.5
No. Observations:                4348   AIC:                         1.550e+04
Df Residuals:                    4333   BIC:                         1.559e+04
Df Model:                          14
Covariance Type:                  HC1
==================================================================================
                     coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept         -1.0698      0.258     -4.152      0.000      -1.575      -0.565
age                0.1702      0.004     38.746      0.000       0.162       0.179
educ              -0.0729      0.007    -10.311      0.000      -0.087      -0.059
idlnchld           0.0770      0.014      5.323      0.000       0.049       0.105
knowmeth           0.5610      0.174      3.224      0.001       0.220       0.902
usemeth            0.6516      0.052     12.571      0.000       0.550       0.753
agefm             -0.0606      0.010     -6.192      0.000      -0.080      -0.041
heduc             -0.0573      0.009     -6.440      0.000      -0.075      -0.040
urban             -0.2190      0.045     -4.814      0.000      -0.308      -0.130
electric          -0.3207      0.063     -5.076      0.000      -0.445      -0.197
bicycle            0.2046      0.048      4.279      0.000       0.111       0.298
nevermarr         -2.2501      0.202    -11.158      0.000      -2.645      -1.855
idlnchld_noans     0.6565      0.216      3.043      0.002       0.234       1.079
heduc_noans       -0.8853      0.191     -4.638      0.000      -1.259      -0.511
usemeth_noans      0.7732      0.212      3.639      0.000       0.357       1.190
==============================================================================
Omnibus:                      224.096   Durbin-Watson:                   1.886
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              856.760
Skew:                           0.004   Prob(JB):                    9.06e-187
Kurtosis:                       5.175   Cond. No.                         345.
==============================================================================

Warnings:
[1] Standard Errors are heteroscedasticity robust (HC1)

In [31]:
print sms.het_breuschpagan(fitted2.resid, fitted2.model.exog)[1]

1.1197458896534061e-228

In [32]:
print "F=%f, p=%f, k1=%f" % m1.fit().compare_f_test(m3.fit())

F=0.919236, p=0.467231, k1=5.000000

In [33]:
# new_df.drop(['usemeth_noans', 'usemeth'],axis=1, inplace=True)
# new_df.head()

In [34]:
m4 = smf.ols('ceb ~ age + educ + idlnchld + knowmeth + agefm +'\
                    'heduc + urban + electric + bicycle + nevermarr +'\
                    'idlnchld_noans + heduc_noans', 
                    data=new_df)
fitted4 = m4.fit(cov_type='HC1')
print fitted4.summary()

                            OLS Regression Results
==============================================================================
Dep. Variable:                    ceb   R-squared:                       0.629
Model:                            OLS   Adj. R-squared:                  0.628
Method:                 Least Squares   F-statistic:                     396.4
Date:                Mon, 06 May 2019   Prob (F-statistic):               0.00
Time:                        16:52:38   Log-Likelihood:                -7825.7
No. Observations:                4348   AIC:                         1.568e+04
Df Residuals:                    4335   BIC:                         1.576e+04
Df Model:                          12
Covariance Type:                  HC1
==================================================================================
                     coef    std err          z      P>|z|      [0.025      0.975]
----------------------------------------------------------------------------------
Intercept         -1.1931      0.262     -4.562      0.000      -1.706      -0.681
age                0.1776      0.004     41.592      0.000       0.169       0.186
educ              -0.0560      0.007     -7.788      0.000      -0.070      -0.042
idlnchld           0.0705      0.015      4.748      0.000       0.041       0.100
knowmeth           0.8739      0.174      5.029      0.000       0.533       1.214
agefm             -0.0649      0.010     -6.489      0.000      -0.085      -0.045
heduc             -0.0521      0.009     -5.658      0.000      -0.070      -0.034
urban             -0.1866      0.046     -4.019      0.000      -0.278      -0.096
electric          -0.3218      0.065     -4.953      0.000      -0.449      -0.194
bicycle            0.1979      0.048      4.083      0.000       0.103       0.293
nevermarr         -2.3625      0.205    -11.498      0.000      -2.765      -1.960
idlnchld_noans     0.5266      0.225      2.343      0.019       0.086       0.967
heduc_noans       -0.7947      0.195     -4.070      0.000      -1.177      -0.412
==============================================================================
Omnibus:                      250.641   Durbin-Watson:                   1.910
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              936.515
Skew:                          -0.158   Prob(JB):                    4.35e-204
Kurtosis:                       5.251   Cond. No.                         345.
==============================================================================

Warnings:
[1] Standard Errors are heteroscedasticity robust (HC1)

In [35]:
print m3.fit().compare_f_test(m4.fit())[1]

3.1552009480371243e-40